<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class OrdersSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('orders')->truncate();
        Schema::enableForeignKeyConstraints();
        DB::table('orders')->insert([
            [
                'id' => 1,
                'ma_don_hang' => 'DH001',
                'hinh_anh' => 'https://robotnoidianhat.com/wp-content/uploads/2021/05/810-3.jpg',
                'so_luong' => 1,
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'ten_nguoi_nhan' => 'Nguyễn Diệp Thanh Bình',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 35000,
                'tong_tien' => 45000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => '2025-02-19 10:34:00',
                'updated_at' => '2025-02-19 10:34:00',
            ],
            [
                'id' => 2,
                'ma_don_hang' => 'DH002',
                'hinh_anh' => 'https://robothutbui.vn/wp-content/uploads/2020/03/LG_CordZero_R9MASTER_B01.jpg',
                'so_luong' => 1,
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'ten_nguoi_nhan' => 'Phạm Thị Kiều',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 25000,
                'tong_tien' => 33000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => '2025-02-20 14:00:00',
                'updated_at' => '2025-02-20 14:00:00',
            ],
            [
                'id' => 3,
                'ma_don_hang' => 'DH003',
                'hinh_anh' => 'https://bigshop.vn/media/product/250_2536_robot_hut_bui_thong_minh_philips_fc8776_700.jpg',
                'so_luong' => 1,
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'ten_nguoi_nhan' => 'Trần Đức Tuấn',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 55000,
                'tong_tien' => 67000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => '2025-02-22 11:45:00',
                'updated_at' => '2025-02-22 11:45:00',
            ],
            [
                'id' => 4,
                'ma_don_hang' => 'DH004',
                'hinh_anh' => 'https://robotnoidianhat.com/wp-content/uploads/2021/05/810-3.jpg',
                'so_luong' => 1,
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'ten_nguoi_nhan' => 'Lê Thúy Dương',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 30000,
                'tong_tien' => 40000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => '2025-03-01 13:22:00',
                'updated_at' => '2025-03-01 13:22:00',
            ],
            [
                'id' => 5,
                'ma_don_hang' => 'DH005',
                'hinh_anh' => 'https://bigshop.vn/media/product/250_2536_robot_hut_bui_thong_minh_philips_fc8776_700.jpg',
                'so_luong' => 1,
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'ten_nguoi_nhan' => 'Đặng Văn Hiếu',
                'so_dien_thoai' => '0966554433',
                'tien_hang' => 45000,
                'tong_tien' => 57000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => '2025-03-05 15:30:00',
                'updated_at' => '2025-03-05 15:30:00',
            ],
            [
                'id' => 6,
                'ma_don_hang' => 'DH006',
                'hinh_anh' => 'https://robothutbui.vn/wp-content/uploads/2020/03/LG_CordZero_R9MASTER_B01.jpg',
                'so_luong' => 1,
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'ten_nguoi_nhan' => 'Đặng Văn Hiếu',
                'so_dien_thoai' => '0966554433',
                'tien_hang' => 50000,
                'tong_tien' => 60000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => '2025-03-10 10:15:00',
                'updated_at' => '2025-03-10 10:15:00',
            ],
            [
                'id' => 7,
                'ma_don_hang' => 'DH007',
                'hinh_anh' => 'https://irobot.vn/wp-content/uploads/2021/01/irobot-roomba-i7-plus.jpg',
                'so_luong' => 1,
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'ten_nguoi_nhan' => 'Lê Thúy Dương',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 25000,
                'tong_tien' => 37000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => '2025-03-15 11:45:00',
                'updated_at' => '2025-03-15 11:45:00',
            ],
            [
                'id' => 8,
                'ma_don_hang' => 'DH008',
                'hinh_anh' => 'https://irobot.vn/wp-content/uploads/2021/01/irobot-roomba-i7-plus.jpg',
                'so_luong' => 2,
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'ten_nguoi_nhan' => 'Nguyễn Diệp Thanh Bình',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 40000,
                'tong_tien' => 50000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => '2025-03-20 16:00:00',
                'updated_at' => '2025-03-20 16:00:00',
            ],
            [
                'id' => 9,
                'ma_don_hang' => 'DH009',
                'hinh_anh' => 'https://robothutbui.vn/wp-content/uploads/2020/03/LG_CordZero_R9MASTER_B01.jpg',
                'so_luong' => 1,
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'ten_nguoi_nhan' => 'Phạm Thị Kiều',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 30000,
                'tong_tien' => 40000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => '2025-03-25 09:30:00',
                'updated_at' => '2025-03-25 09:30:00',
            ],
            [
                'id' => 10,
                'ma_don_hang' => 'DH010',
                'hinh_anh' => 'https://robothutbui.vn/wp-content/uploads/2020/03/LG_CordZero_R9MASTER_B01.jpg',
                'so_luong' => 1,
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'ten_nguoi_nhan' => 'Trần Đức Tuấn',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 45000,
                'tong_tien' => 57000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => '2025-04-01 14:15:00',
                'updated_at' => '2025-04-01 14:15:00',
            ],
        ]);
    }
}
